name: grumpy_gen
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.11.4

# Add regular dependencies here.
dependencies:
  analyzer: ^10.0.1
  build: ^4.0.5
  source_gen: ^4.2.2
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
